name: Build & Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to AWS CloudFront
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      
